@baseUrl = http://localhost:8080

### LOGIN
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

### REGISTER
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password",
    "fullName": "Sample Name"
}

### REFRESH
GET {{baseUrl}}/api/v1/auth/refresh
Content-Type: application/json

### VERIFY EMAIL
POST {{baseUrl}}/api/v1/auth/verify-email?token=
Content-Type: application/json

### RESET PASSWORD
POST {{baseUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "test@example.com"
}

### CREATE PASSWORD
POST {{baseUrl}}/api/v1/auth/create-password
Content-Type: application/json

{
     "password": "password",
     "resetToken": ""
}

### GOOGLE OAUTH
GET {{baseUrl}}/api/v1/auth/google
Content-Type: application/json

### GOOGLE OAUTH CALLBACK
POST {{baseUrl}}/api/v1/auth/google/callback?code=some-code&state=some-state
Content-Type: application/json