export const DEFAULT_CATEGORIES = {
    inflow: [
        'Salary',
        'Business Income',
        'Investments',
        'Freelance/Contracting',
        'Gifts',
        'Rental Income',
        'Bonuses',
        'Refunds/Reimbursements',
        'Royalties',
        'Grants/Scholarships'
    ],
    outflow: [
        'Housing',
        'Groceries',
        'Dining Out',
        'Fuel',
        'Public Transport',
        'Car Maintenance',
        'Health Insurance',
        'Medical Bills',
        'Gym/Fitness',
        'Entertainment',
        'Streaming Services',
        'Hobbies',
        'Education',
        'Courses',
        'Books/Supplies',
        'Clothing',
        'Personal Care',
        'Travel',
        'Debt Payments',
        'Loan Repayment',
        'Credit Card Payments',
        'Savings',
        'Investments',
        'Gifts',
        'Charitable Donations',
        'Life Insurance',
        'Car Insurance'
    ]
};
